import authorImg from "./assets/images/authors/avloniy.svg";
import bookImg from "./assets/images/books/book.svg";

export const authorsData = [
  {
    _id: 1,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 2,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 3,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 4,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 5,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 6,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 7,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 8,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 9,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 10,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
  {
    _id: 11,
    img: authorImg,
    firstName: "Abdulla",
    lastName: "Avloniy",
    date_of_birth: "1874",
    date_of_death: "1934",
    books: 34,
    audios: 13,
  },
];

export const booksData = [
  {
    _id: 1,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 2,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 3,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 4,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 5,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 6,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 7,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 8,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 9,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 10,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 11,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 12,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 13,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
  {
    _id: 14,
    name: "Dunyoning ishlari",
    author: "O'tkir Hoshimov",
    point: 4.1,
    feedback: 1300,
    img: bookImg,
  },
];
